---
title: "In-class Assignment 7"
author: "Andrew Shao"
date: "2024-10-16"
output: pdf_document
header-includes: 
  - \usepackage{tikz}
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 7.1.4 Q1
```{r}
library(r02pro)
library(tidyverse)

my_ahp <- ahp %>% filter(yr_built < 2000,
                         yr_sold >= 2009,
                         bedroom  %in% c(2, 3))

my_ahp
```

## 7.1.4 Q2
```{r}
my_gm <- gm %>% filter(continent %in% c('Asia', 'Africa'),
                       HDI_category %in% c('medium', 'high'),
                       year == 2006)

my_gm
```

## 7.2.5 Q1
```{r}
ahp %>%
  select(date_sold = dt_sold,
         house_type = house_style,
         liv_area,
         sale_price)
```

## 7.2.5 Q2
```{r}
ahp %>%
  select(starts_with('yr'),
         ends_with('qual'))
```

## 7.3.1 Q1
```{r}
ahp %>%
  filter(yr_built == 2008,
         house_style == '2Story') %>%
  arrange(yr_remodel, desc(sale_price))
```

## 7.3.1 Q2
```{r}
ahp %>%
  filter(yr_sold == 2009,
         house_style == '1Story') %>%
  arrange(desc(sale_price))
```